name: Build workflow

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '8.0'
          - '8.1'
          - '8.2'

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Check PHP version
        run: php -v

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run analyze
        run: composer analyze

      - name: Run cs check
        run: composer cs-check

      - name: Run unit tests
        run: composer unittests